### ISSUE TITLE
Do not use `.` in labels in the flatten function of converter.go

### ISSUE THREAD

**Issue by kyasbal** [samber/slog-loki#10]
I'm using `slog-loki` just for my personal project. I've tried the newer version with updating the client of loki before merging #5 .

I found `slog-loki` might need to convert label names in different way.

https://github.com/samber/slog-loki/blob/7da5375f71747fbcb16b867c18f21a92991405db/converter.go#L39-L55

The function is using `.` to express enclosed slog.Attrs. But this seems not to be allowed in loki[1].

I tweaked that to use `_` in my usecase and it's easy to send a PR for this fix. But this solution might be not the ideal that the auhor of this library think of.

[1]https://grafana.com/docs/loki/latest/get-started/labels/#format

**Comment by samber** [comment]
Hi @kyasbal and thanks for the bug report.

I would suggest `__` separators (double `_`), to prevent collision with user defined `_`.

Using `:` would be even better IMO, but Prometheus recommends not using it. Moreover it looks like it is only available for `__name__` label name...

**Comment by samber** [comment]
added in v3.1.0
