### ISSUE TITLE
`slog-loki` may need to convert `-` in labels to another character

### ISSUE THREAD

**Issue by kyasbal** [samber/slog-loki#11]
This is quite relevant to another issue #10.

That was about the character used in this library itself, thus it should be fixed on this library side.
But this issue is about the other characters especially about `-`.

`slog-echo` is using `-` in the label name for example.

https://github.com/samber/slog-echo/blob/bbb3b8d417a6a6afeb828047829eccbc2ec46a56/middleware.go#L180-L187

This is not the character supported in Loki[1]. `slog-loki` may need to escape them to another character?

[1]https://grafana.com/docs/loki/latest/get-started/labels/#format

**Comment by samber** [comment]
I would suggest rewriting any non-supported char to `_`. WDYT ?

**Comment by samber** [comment]
added in v3.1.0
