### ISSUE TITLE
Log in JSON style

### ISSUE THREAD

**Issue by simonostendorf** [samber/slog-loki#12]
How can i log messages in json format?

Currently my log messages in loki look like this:
![image](https://github.com/samber/slog-loki/assets/70595012/b3a649ee-f800-4b1a-bbae-3e9104e916af)

**Comment by samber** [comment]
I'm not sure to understand your needs.

This lib is intended to push logs in the loki format. 

Your screenshot is showing that loki+grafana properly interpreted the logs.

**Comment by simonostendorf** [comment]
Please excuse the inaccuracy.
I have always used Loki in such a way that the logs that (in this case) Promtail sends are all in JSON format and are then displayed as such and not (as shown in the image) with individual fields.

So my question was whether I could somehow send the logs I generate with slog to Loki as JSON using this Loki library.
This would also allow groups in the log attributes that don't get flattened.

I hope that makes my question clearer.

**Comment by samber** [comment]
Sorry, it's not clear to me.

Can you make an example, please?

**Comment by simonostendorf** [comment]
> Sorry, it's not clear to me.
> 
> Can you make an example, please?

In the past I used loki with logs in json format (see [this example](https://global.discourse-cdn.com/grafana/original/3X/3/d/3db81cfadbf1b6134ef21068522a2949069cf280.png)). 

Currently my logs are in text format. See this example: [image](https://github.com/samber/slog-loki/assets/70595012/72c230fd-cc76-4645-a50f-5e77e3165006).

So I want to change the message "Hi" (in my example) to show all fields as json as shown in the first example.
After writing this comment I thought about setting "msg" to a json string with all my fields. If this is possible this issue can be closed, sorry :)

Sorry if it's not clear, I don't know how to explain it and I'm new to loki development :D

**Comment by samber** [comment]
I suppose you can use samber/slog-multi to reformat your log record and pass to samber/slog-loki a simple json.
