### ISSUE TITLE
endpoint example

### ISSUE THREAD

**Issue by abh** [samber/slog-loki#2]
with the endpoint example of

    endpoint := "localhost:3100"

the slog-loki (promclient really) gives an error of

    time=2023-07-29T13:28:02.365-07:00 level=INFO msg="promtail.ClientJson: unable to send an HTTP request: Post \"localhost:3100\": unsupported protocol scheme \"localhost\""

**Comment by samber** [comment]
This right endpoint is:

```go
endpoint := "http://localhost:3100"
```

I'm going to fix the readme.
