### ISSUE TITLE
x-scope-orgid

### ISSUE THREAD

**Issue by till** [samber/slog-loki#3]
Hey 👋🏼 — I was looking through this code. I saw you used the same promtail client we use internally. Since the development stalled, we updated it in a fork to e.g. support `x-scope-orgid` in promtail. I wanted to ask if you'd be up for pulling our fork in, so we can support this in your handler?

Here's a diff of changes:
https://github.com/afiskon/promtail-client/compare/master...hostwithquantum:promtail-client:pnmain

Till

**Comment by samber** [comment]
Hi @till 

I refactored this lib using a new Loki client -> https://github.com/samber/slog-loki/pull/5

Can you test the example in the branch with your authentication, please? You should be able to customize the Loki client now.

**Comment by samber** [comment]
v3 has been released

**Comment by till** [comment]
@samber Cheers! Sorry I didn't respond earlier, but using the official client seems like a good choice.

I think we stayed away from it back then because of the license drama, but it looks permissive now. :)
