### ISSUE TITLE
Confused by how to use this package

### ISSUE THREAD

**Issue by ChristoWolf** [samber/slog-loki#6]
Hi @samber!

I seem to not understand how to use this package.
When I configure the endpoint as in your example (just with the hostname of the actual server), I get the following output:
```
time=2023-11-10T12:16:08.199+01:00 level=INFO msg="promtail.ClientJson: Unexpected HTTP status code: 200, message: OK"
```

These entries are not logged when using the `https://{YOUR_LOKI_ENDPOINT}/loki/api/v1/push` endpoint, which is [the usual one accepted by Promtail](https://grafana.com/docs/loki/latest/send-data/promtail/installation/#:~:text=https%3A//%7BYOUR_LOKI_ENDPOINT%7D/loki/api/v1/push).
So I guess I have configured the correct endpoint?

However, I cannot find the logs anywhere in my Grafana instance with the Loki server being configured as the data source.
No labels are generated (should those be the keys in my log entries?) and thus I cannot query any.

This is my configuration (importing `github.com/samber/slog-loki/v2` and `github.com/samber/slog-multi`):
```go
logger := slog.New(
	slogmulti.Fanout(
		slogloki.Option{Level: slog.LevelDebug, Endpoint: lokiEndpoint}.NewLokiHandler(),
		slog.NewTextHandler(os.Stdout, &slog.HandlerOptions{Level: slog.LevelDebug}),
		slog.NewJSONHandler(f, &slog.HandlerOptions{Level: slog.LevelDebug})))
host, err := os.Hostname()
if err != nil {
	logger.Error("Failed to get hostname!", "error", err)
	os.Exit(1)
}
logger = logger.With("tool", toolName)
logger = logger.With("hostname", host)
```

Any help would be great!

**Comment by kyasbal** [comment]
Hi @ChristoWolf , I actually face same issue and I realized there are 2 different APIs for pushing log entry. These are `/loki/api/v1/push` and `/api/prom/push`.

`/api/prom/push` seems to be deprecated but this library seems to depend promtail-client which depends on the API.
I could see the log entries from my Grafana instance when I use the endpoint ends with `/api/prom/push`.

**Comment by ChristoWolf** [comment]
Hi @kyasbal!

This is really good to know, thanks!
But it also increases my confusion further :/

**Comment by samber** [comment]
I didn't find good Loki client, so i leveraged the Promtail library.

Let me fix the documentation.

**Comment by ChristoWolf** [comment]
@samber Awesome, thanks!

**Comment by samber** [comment]
Oops sorry guys.

A PR moving to a Loki library was still pending.

Please upgrade to v3 !!

**Comment by ChristoWolf** [comment]
@samber Awesome, thanks!
